var aos = aos || {};
aos.lang = aos.lang || {};

aos.lang.username_and_email_are_required = 'Необходимо указать Имя пользователя и Email';
aos.lang.invalid_email = 'Указан некорректный электронный адрес';
aos.lang.small_pwds = 'Минимальная длина пароля 5 символов';
aos.lang.pwds_not_equals = 'Введенные пароли на совпадают';
aos.lang.user_already_registered = 'Пользователь с таким электронным адресом уже зарегистрирован';
aos.lang.all_fields_are_required = 'Все поля являются обязательными';
aos.lang.invalid_pwds = 'Длина паролей должна быть не менее 5 символов и они должны совпадать';
aos.lang.invalid_role = 'Указана некорректная роль, выберите роль из предложенного списка';
aos.lang.invalid_username = 'Имя пользователя не может быть пустым или более 30 символов';
aos.lang.something_goes_wrong = 'Упс, что-то пошло не так.. Попробуй снова';
aos.lang.user_not_registered = 'Не удалось войти, проверь правильность Email и пароля';
aos.lang.order_title_is_required = 'Необходимо указать заголовок заказа';
aos.lang.order_content_is_required = 'Необходимо описание заказа, чтобы исполнитель понимал детали';
aos.lang.order_price_is_required = 'Необходимо указать цену за выполнение заказа';
aos.lang.invalid_order_price = 'Указана некорректная стоимость заказа. Наша система позволяет использовать максимум 15 знаков до разделителя и 2 знака после';
aos.lang.negative_order_price = 'Стоимость заказа должна быть больше 0';